### PR TITLE
add makefile and document how to run tests

### PR DESCRIPTION
**Pull request by wilmoore**

### CODE REVIEW

**Comment by mikeal** [comment]
i prefer the $ npm test, target. that's the standard node convention. @maxogden what do you think?

**Comment by wilmoore** [comment]
@mikeal:

I've added `make test` to the `npm test` target in `package.json`. I agree that this is a good pattern. Delegating to the `make test` target has the added benefit of utilizing task dependencies to ensure `npm install` gets run the first time and subsequently when `package.json` is updated.

**Comment by wilmoore** [comment]
Oh, and I also noticed that I needed to add some missing deps.

**Comment by mikeal** [comment]
those must be due to @maxogden's latest patch for stream support.

**Comment by max-mapper** [comment]
thanks @wilmoore. I also gave a little love to the readme. gonna work on expanding the test suite now and do some benchmarking as I'm nearing a release of `dat`

**Comment by wilmoore** [comment]
:+1:

**Pull request merged**
